require 'chunky_png'
include ChunkyPNG::Color

WIDTH = 169
HEIGHT = 93


def generate_art(input: "metanet.png", sensitivity: 0.5, title: "autogenerated map")
  image = ChunkyPNG::Image.from_file(input).resample_nearest_neighbor(WIDTH, HEIGHT)
  output = ChunkyPNG::Image.new(WIDTH, HEIGHT, WHITE)
  $objects = []
  HEIGHT.times do |y|
    WIDTH.times do |x|
      score = euclidean_distance_rgba(image[x,y], WHITE) / MAX_EUCLIDEAN_DISTANCE_RGBA
      gray = (MAX * (1 - score)).round
      if gray < 128
        output[x,y] = grayscale(gray)
        $objects << []
      end
    end
  end
  output.save("metanet_new.png")
end

